version: 2.1

dockerhub_auth: &dockerhub_auth
  auth:
    username: kuldeepiitg
    password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

hello_world_steps: &hello_world_steps
  steps:
    - run:
        name: Saying Hello
        command: |
          echo 'Hello World!'
          echo 'This is the delivery pipeline'

jobs:
  # running commands on a basic image
  Hello-World:
    docker:
      - image: alpine:3.15
        <<: *dockerhub_auth
    <<: *hello_world_steps
  # fetching code from the repo
  Fetch-Code:
    docker:
      - image: cimg/base:2021.04
        <<: *dockerhub_auth
    steps:
      - checkout
      - run:
          name: Getting the Code
          command: |
            ls -al
            echo '^^^Your repo files^^^'
  # running a node container
  Using-Node:
    docker:
      - image: cimg/node:17.2
        <<: *dockerhub_auth
    steps:
      - run:
          name: Running the Node Container
          command: |
            node -v
  Now-Complete:
    docker:
      - image: alpine:3.15
        <<: *dockerhub_auth
    steps:
      - run:
          name: Approval Complete
          command: |
            echo 'The work is now complete.'

workflows:
  Example-Workflow:
    jobs:
      - Hello-World
      - Fetch-Code:
          requires:
            - Hello-World
      - Using-Node:
          requires:
            - Fetch-Code
      - Hold-for-Approval:
          type: approval
          requires:
            - Using-Node
            - Fetch-Code
      - Now-Complete:
          requires:
            - Hold-for-Approval